name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - rusttarget: aarch64-unknown-linux-gnu
            zigtarget: aarch64-linux-gnu
          - rusttarget: x86_64-unknown-linux-gnu
            zigtarget: x86_64-linux-gnu
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: limbo
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: neodyland/cross-rust-action@v0.0.7
        with:
          zigtarget: ${{ matrix.zigtarget }}
          rusttarget: ${{ matrix.rusttarget }}
          cargo-build-args: --release
      - name: Rename artifact
        run: |
          mkdir .out
          mv target/${{ matrix.rusttarget }}/release/limbo .out/${{ matrix.zigtarget }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}